-- Remaining RLS policies (kept together here because several reference
-- tables that only exist once the full schema above has been created).
--
-- Shape used throughout:
--   - chu_hui / pho_chu_hui: full read+write on organizational data.
--   - ke_toan: full read, write limited to payments/bids (their job).
--   - thanh_vien: read-only, scoped to rows tied to their own member_id.
--   - Tables mutated only via close_period()/open_period() (periods,
--     chain_shares winner fields, period_bid_distributions) get select-only
--     policies here — writes bypass RLS because those functions are owned
--     by the migration role, which Postgres exempts from RLS by default.

-- hui_chains ------------------------------------------------------------
create policy hui_chains_select on hui_chains for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or exists (
      select 1 from chain_members cm
      where cm.chain_id = hui_chains.id and cm.member_id = my_member_id()
    )
  );

create policy hui_chains_insert on hui_chains for insert
  to authenticated
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui'));

create policy hui_chains_update on hui_chains for update
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui'))
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui'));

create policy hui_chains_delete on hui_chains for delete
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui'));

-- chain_members -----------------------------------------------------------
create policy chain_members_select on chain_members for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or member_id = my_member_id()
  );

create policy chain_members_insert on chain_members for insert
  to authenticated
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui'));

create policy chain_members_update on chain_members for update
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui'))
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui'));

create policy chain_members_delete on chain_members for delete
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui'));

-- chain_shares --------------------------------------------------------------
create policy chain_shares_select on chain_shares for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or exists (
      select 1 from chain_members cm
      where cm.id = chain_shares.chain_member_id and cm.member_id = my_member_id()
    )
  );

create policy chain_shares_insert on chain_shares for insert
  to authenticated
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui'));

create policy chain_shares_delete on chain_shares for delete
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui'));

-- periods (mutated only via open_period/close_period) ------------------------
create policy periods_select on periods for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or exists (
      select 1 from chain_members cm
      where cm.chain_id = periods.chain_id and cm.member_id = my_member_id()
    )
  );

-- period_bids -----------------------------------------------------------
create policy period_bids_select on period_bids for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or exists (
      select 1 from chain_shares cs
      join chain_members cm on cm.id = cs.chain_member_id
      where cs.id = period_bids.chain_share_id and cm.member_id = my_member_id()
    )
  );

create policy period_bids_insert on period_bids for insert
  to authenticated
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan'));

create policy period_bids_update on period_bids for update
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan'))
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan'));

create policy period_bids_delete on period_bids for delete
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan'));

-- period_bid_distributions (written only by close_period()) --------------
create policy period_bid_distributions_select on period_bid_distributions for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or exists (
      select 1 from chain_shares cs
      join chain_members cm on cm.id = cs.chain_member_id
      where cs.id = period_bid_distributions.chain_share_id and cm.member_id = my_member_id()
    )
  );

-- payments (due rows generated by open_period()) --------------------------
create policy payments_select on payments for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or exists (
      select 1 from chain_shares cs
      join chain_members cm on cm.id = cs.chain_member_id
      where cs.id = payments.chain_share_id and cm.member_id = my_member_id()
    )
  );

-- payment_records (recording a payment is direct client-side CRUD) --------
create policy payment_records_select on payment_records for select
  to authenticated
  using (
    current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan')
    or exists (
      select 1 from payments p
      join chain_shares cs on cs.id = p.chain_share_id
      join chain_members cm on cm.id = cs.chain_member_id
      where p.id = payment_records.payment_id and cm.member_id = my_member_id()
    )
  );

create policy payment_records_insert on payment_records for insert
  to authenticated
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan'));

create policy payment_records_delete on payment_records for delete
  to authenticated
  using (current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan'));

-- notifications -----------------------------------------------------------
create policy notifications_select on notifications for select
  to authenticated
  using (profile_id = auth.uid() or profile_id is null);

create policy notifications_update on notifications for update
  to authenticated
  using (profile_id = auth.uid() or profile_id is null)
  with check (profile_id = auth.uid() or profile_id is null);

create policy notifications_insert on notifications for insert
  to authenticated
  with check (current_role_name() in ('chu_hui', 'pho_chu_hui', 'ke_toan'));

-- activity_log (every server action logs its own actor) -------------------
create policy activity_log_select on activity_log for select
  to authenticated
  using (true);

create policy activity_log_insert on activity_log for insert
  to authenticated
  with check (actor_id = auth.uid());
